#
#   $Id: ./uum.msg $
#

#
# FreeWnn is a network-extensible Kana-to-Kanji conversion system.
# This file is part of FreeWnn.
# 
# Copyright Kyoto University Research Institute for Mathematical Sciences
#                 1987, 1988, 1989, 1990, 1991, 1992
# Copyright OMRON Corporation. 1987, 1988, 1989, 1990, 1991, 1992, 1999
# Copyright ASTEC, Inc. 1987, 1988, 1989, 1990, 1991, 1992
# Copyright FreeWnn Project 1999, 2000
# 
# Maintainer:  FreeWnn Project   <freewnn@tomo.gr.jp>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

###	massage file for uum
### jhlp.c
1	\r\t·····你好·····\r\n\t·欢迎使用汉语处理系统·\r\n\t·  祝您今天好运气　　·\r\n\t····ｃｕｕｍ····\r\n
2	Malloc失败了。
3	\r\nｃｕｕｍ结束。\r\n
4	在ｃｕｕｍ上不能起动ｃｕｕｍ。\n
5	太凄苦！侯补太多　次侯补不能取出。
6	 国标代码: 
7	区位 : 
8	 (怎么办)
9	 cserver的连接断开了。(怎么办?)
10	 连接中···
11	 连接ｈｏｓｔ名 > 
12	 连接不通顺。(怎么办?)
13	 连接失败。(怎么办?)
14	缺省的 uumrc 没有。
15	返回前面
16	 频度:%c%d
17	评价值:%d 前端向量No.:%d
18	大文节评价值
19	  读取:
20	消除吗?(Y/N)
21	固定形式的字典的条目不能消除。(怎么办)
22	只读的字典的条目不能消除。(怎么办)
23	「
24	」消除。(Y/N)
25	只读的频度不能变更。(怎么办)
26	」的使用中止。(Y/N)
27	 没有。(怎么办)
28	缺省的uumkey异常。 %s\n
29	uumkey: %s 不能展开。\r\n
30	uumkey: %s(0x%x)的键二重定义。at line %d (%s)(table No. %d).\r\n
31	字典「
32	」重新使用。(Y/N)
33	1:字典 2:频度 哪一个设置注释。>
34	1 或 2 请指定。(怎么办)
35	注释: 
36	固定形式字典的条目的注释不能变更。(怎么办)
37	只读字典的条目的注释不能变更。(怎么办)
38	登录结束:
39	登录开始:
40	字典: 
41	  读法:
42	登录可能形式的字典一个也没有。
43	登录范围长度超过。(怎么办)
44	读取长度超过。(怎么办)
45	现在 %d文节解析法在使用。使用什么文节解析法 ?
46	现在的%s是 %d、变成多大  ?
47	请输入数字。(怎么办)
48	请输入正的数字。(怎么办)
49	现在、字典的频度和用户字典正在保存。
50	遗憾、字典太大。
51	字典一个也没有。
52	使用中
53	中断中
54	文法文件名 >
55	新的字典 >
56	频度文件名 >
57	请指定字典的优先度的数字。 >
58	使用字典更新摸式吗?(Y or Newline / N)
59	使用频度更新摸式吗?(Y or Newline / N)
60	现在、读取字典。
61	字典追加
62	字典一览
63	登录
64	检索
65	参数变更
66	频度保存
67	字典情报
68	文法变更
69	结束
70	解析词组个数
71	词组中词的最大个数
72	频度权值
73	词长度权值
74	四声正确度权值
75	刚才用过权值
76	字典优先级权值
77	词评价均值权值
78	词组长权值
79	词组中词数权值
80	数字的频度
81	英文字母的频度
82	记号的频度
83	开括弧的频度
84	闭括弧的频度
85	最大候补个数
86	备用 
87	No.
88	Type
89	注释
90	文件名
91	频度文件名
92	词条数
93	优先度
94	可以登录
95	频度可以更新
96	使用中吗
97	登录password
98	频度更新password
99	频度
