#
#   $Id: ./wnnstat.msg $
#

#
# FreeWnn is a network-extensible Kana-to-Kanji conversion system.
# This file is part of FreeWnn.
# 
# Copyright Kyoto University Research Institute for Mathematical Sciences
#                 1987, 1988, 1989, 1990, 1991, 1992
# Copyright OMRON Corporation. 1987, 1988, 1989, 1990, 1991, 1992, 1999
# Copyright ASTEC, Inc. 1987, 1988, 1989, 1990, 1991, 1992
# Copyright FreeWnn Project 1999, 2000
# 
# Maintainer:  FreeWnn Project   <freewnn@tomo.gr.jp>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

1	Env No.\t环境名\t参照数\t文法\t词典数(词典No.)\t\t文件\n
2	Env No.\t环境名\t参照数\n
3	用户名:ｈｏｓｔ名\t(接口No.)\t环境号码\n
4	No.\t种类\t注释\t文件\t\n
5	No.种类\t正/逆\t语数\t更新(频)使用 优先级\t[俗称]\t文件[(频度)]\t[password(频度)]\n
6	逆变换
7	正变换
8	不
9	可
10	中
11	停止
12	Fid\t种类\t场合\t参照数\t\t文件名\n
13	词典
14	频度
15	语法
