.\"
.\"   $Id: ./cwnnkill.man $
.\"
.\"
.\" FreeWnn is a network-extensible Kana-to-Kanji conversion system.
.\" This file is part of FreeWnn.
.\" 
.\" Copyright Kyoto University Research Institute for Mathematical Sciences
.\"                 1987, 1988, 1989, 1990, 1991, 1992
.\" Copyright OMRON Corporation. 1987, 1988, 1989, 1990, 1991, 1992, 1999
.\" Copyright ASTEC, Inc. 1987, 1988, 1989, 1990, 1991, 1992
.\" Copyright FreeWnn Project 1999, 2000
.\" 
.\" Maintainer:  FreeWnn Project   <freewnn@tomo.gr.jp>
.\" 
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.\"
.TH CWNNKILL \  "13 May 1992"
.SH NAME
cwnnkill \- To terminate the cserver.
.SH SYNOPSIS
cwnnkill  [-L 
.I lang
]  [
.I hostname
]
.SH DEFAULT PATH
/usr/local/bin/cWnn4/cwnnkill
.ad
.SH DESCRIPTION
To terminate the cserver.  
.sp 0
If 
.I hostname 
is given, the cserver at the specified host will be terminated. 

If no 
.I hostname 
is given, "cwnnkill" will terminate the cserver of 
UNIX_domain.  This is the cserver specified in the environment variable 
CSERVER.  If this environment variable is not specified, "cwnnkill" 
will terminate the cserver of the local machine.

If some other front-end processors are still using the cserver to be killed, 
the current usage condition of the cserver will be shown, and termination 
will fail.  
.SH OPTIONS
.IP -L 
To specify the language name which is referred during selection of cserver.
If no 
.I lang 
is specified, the one specified by the environment variable 
LANG will be used.  The default is "zh_CN".
.SH NOTE
The hostname inside [ ] shown in the Command Format indicates that it is 
optional.  If this option is not required, "cwnnkill" alone is sufficient 
to terminate the cserver.

