#
#   $Id: ./libwnn.msg $
#
#
# FreeWnn is a network-extensible Kana-to-Kanji conversion system.
# This file is part of FreeWnn.
# 
# Copyright Kyoto University Research Institute for Mathematical Sciences
#                 1987, 1988, 1989, 1990, 1991, 1992
# Copyright OMRON Corporation. 1987, 1988, 1989, 1990, 1991, 1992, 1999
# Copyright ASTEC, Inc. 1987, 1988, 1989, 1990, 1991, 1992
# Copyright FreeWnn Project 1999, 2000
# 
# Maintainer:  FreeWnn Project   <freewnn@tomo.gr.jp>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
###	massage file for libwnn.a
### wnnerrmsg.c
#0	no_error 0
1	화일이 존재하지 않습니다.
#2	no_error 2
3	메모리 alloc 에서 실패했읍니다.
#4	no_error 4
5	사전이 아닙니다.
6	빈도 화일이 아닙니다.
7	부속어 화일이 아닙니다.
#8	no_error 8
9	사전 테이블이 꽉 찼읍니다.
10	지정된 사전의 빈도 화일이 아닙니다.
#11	no_error 11
#12	no_error 12
#13	no_error 13
#14	no_error 14
#15	no_error 15
16	화일을 열 수 없읍니다.
17	맞는 빈도 화일이 아닙니다.
18	맞는 부속어 화일이 아닙니다.
19	부속어의 갯수가 너무 많거나 벡터의 길이가 너무 깁니다.
20	그 번호의 사전은 사용되고 있지 않습니다.
#21	no_error 21
#22	no_error 22
#23	no_error 23
24	부속어 화일의 내용이 맞지 않습니다.
25	가상 품사의 번호가 틀립니다. hinsi.data 가 맞지 않습니다.
26	미정의의 품사가 전단 품사로 정의되어 있습니다.
27	부속어 화일이 읽혀져 있지 않습니다.
#28	no_error 28
#29	no_error 29
30	사전의 엔트리가 너무 많습니다.
31	변환하려는 문자열이 너무 깁니다.
32	부속어 해석 영역이 부족합니다.
#33	no_error 33
34	다음 후보 영역이 부족합니다.
35	후보가 없읍니다.
#36	no_error 36
#37	no_error 37
#38	no_error 38
#39	no_error 39
40	한글이 너무 깁니다.
41	한자가 너무 깁니다.
42	지정된 사전은 등록 불가능입니다.
43	한글의 길이가 0 입니다.
44	지정된 사전은 역참조 불가능입니다.
45	읽기전용 사전에 등록/소거 하려고 했읍니다.
46	존재하지 않는 사전에 등록 하려고 했읍니다.
#47	no_error 47
#48	no_error 48
49	읽기전용 빈도를 경신 하려고 했읍니다.
50	지정된 단어는 존재하지 않습니다.
#51	no_error 51
#52	no_error 52
#53	no_error 53
#54	no_error 54
#55	no_error 55
#56	no_error 56
#57	no_error 57
#58	no_error 58
#59	no_error 59
60	메모리 alloc 에 실패했읍니다.
#61	no_error 61
#62	no_error 62
#63	no_error 63
#64	no_error 64
#65	no_error 65
#66	no_error 66
#67	no_error 67
68	에러가 발생했읍니다.
69	버그(Bug)가 발생했읍니다.
70	서버(Server)가 죽어 있읍니다.
71	alloc에 실패했읍니다.
72	서버(Server) 와 접촉할 수 없읍니다.
73	통신 프로토콜의 버젼이 맞지 않습니다.
74	클라이안트가 생성한 환경이 아닙니다.
#75	no_error 75
#76	no_error 76
#77	no_error 77
#78	no_error 78
#79	no_error 79
80	디렉토리를 만들 수 없읍니다.
#81	no_error 81
#82	no_error 82
#83	no_error 83
#84	no_error 84
#85	no_error 85
#86	no_error 86
#87	no_error 87
#88	no_error 88
#89	no_error 89
90	화일 읽기에 실패했읍니다.
91	화일 쓰기에 실패했읍니다.
92	클라이안트가 읽어 드린 화일이 아닙니다.
93	더 이상의 화일을 읽어 드릴 수 없읍니다.
94	패스워드가 틀립니다.
95	화일이 읽혀져 있읍니다.
96	화일을 소거할 수 없읍니다.
97	화일을 작성할 수 없읍니다.
98	kWnn의 화일이 아닙니다.
99	화일의 I-node 와 FILE_UNIQ 를 일치시킬 수 없읍니다.
100	품사 화일의 크기가 너무 큽니다.
101	품사 화일의 크기가 너무 큽니다.
102	품사 화일이 존재하지 않습니다.
103	품사 화일의 내용이 틀립니다.
#104	no_error 104
105	품사 화일이 읽혀져 있지 않습니다.
106	품사 이름이 틀립니다.
107	품사 번호가 틀립니다.
#108	no_error 108
109	그 조작은 지원되지 않습니다.
110	패스워드가 들어있는 화일을 열 수 없읍니다.
111	uumrc 이 존재하지 않습니다.
112	uumrc 의 형식이 틀립니다.
113	이 이상 환경을 작성할 수 없읍니다.
114	크라이안트가 읽어 드린 화일이 아닙니다.
115	사전에 빈도 화일이 존재하지 않습니다.
116	패스워드 화일을 작성할 수 없읍니다.
### jl.c
200	사전화일
201	이 없읍니다.
202	작성하겠습니까? (Y/N)
203	빈도화일
204	사전과 빈도 \"%s\" 가 맞지 않습니다. 다시 작성하겠습니까? (Y/N)
205	password_file
206	include 의 레벨이 너무 많습니다.
207	화일 \"%s\" 이 열리지 않습니다.
208	화일 \"%s\" 에서 환경설정중에 에러가 발생해서 설정을 중지했습니다. \n
209	을 작성했습니다.
210	directry
###
