#
#   $Id: ./uum.msg $
#
#
# FreeWnn is a network-extensible Kana-to-Kanji conversion system.
# This file is part of FreeWnn.
# 
# Copyright Kyoto University Research Institute for Mathematical Sciences
#                 1987, 1988, 1989, 1990, 1991, 1992
# Copyright OMRON Corporation. 1987, 1988, 1989, 1990, 1991, 1992, 1999
# Copyright ASTEC, Inc. 1987, 1988, 1989, 1990, 1991, 1992
# Copyright FreeWnn Project 1999, 2000
# 
# Maintainer:  FreeWnn Project   <freewnn@tomo.gr.jp>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
###	massage file for uum
### jhlp.c
1	\rkuum(한글 한자 변환 Front End Processor)\r\n
2	Malloc 에 실패했읍니다.
3	\r\nkuum 을 종료합니다.\r\n
4	kuum 에서 kuum 을 기동할 수 없읍니다.\n
5	후보가 너무 많아서 다음 후보를 불러올 수 없읍니다.
6	KSC코드: 
7	구점: 
8	 (어떻게 할까요?))
9	 kserver 와 접촉이 끊어졌읍니다.
10	 접촉중...
11	 접촉 호스트 이름 > 
12	 접촉이 안됩니다.
13	 접촉에 실패했읍니다.
14	uumrc 화일이 없읍니다.
15	전 메뉴로
16	빈도:%c%d
17	평가치:%d 전단 벡터No.:%d
18	대문절 평가치
19	한글:
20	을 소거하겠습니까? (Y/N)
21	고정형식 사전의 엔트리는 소거할 수 없읍니다.
22	읽기전용 사전의 엔트리는 소거할 수 없읍니다.
23	[
24	] 을 소거하겠습니다. (Y/N)
25	읽기전용 빈도는 변경할 수 없읍니다.
26	] 의 사용을 중지합니다. (Y/N)
27	이 없읍니다.
28	기본 키바인딩이 이상합니다. %s\n
29	uumkey: %s 을 전개할 수 없읍니다. \r\n
30	uumkey: %s(0x%x) 키가 이중으로 정의되어 있읍니다. at line %d (%s)(table No. %d).\r\n
31	사전[
32	] 의 사용을 재개합니다. (Y/N)
33	1:사전 2:빈도 어느 쪽에 코멘트를 적겠읍니까? >
34	1 이나 2 를 지정해 주십시오.
35	코멘트: 
36	고정형식 사전의 엔트리의 코멘트는 경신할 수 없읍니다.
37	읽기전용 사전의 엔트리의 코멘트는 경신할 수 없읍니다.
38	등록 종료:
39	등록 시작:
40	사전: 
41	한글:
42	등록가능형식의 사전이 없읍니다.
43	등록범위가 너무 깁니다.
44	한글이 너무 깁니다.
45	현재 %d 문절 해석법을 사용하고 있읍니다. 어떤 문절 해석법을 사용하겠읍니까?
46	현재의 %s 은 %d 입니다. 얼마로 하겠읍니까?
47	숫자를 입력하십시오.
48	양의 수를 입력하십시오.
49	지금 사전 빈도와 유저 사전을 저장하고 있읍니다.
50	사전이 너무 많습니다.
51	사전이 없읍니다.
52	사용중
53	중단중
54	부속어 화일 이름 >
55	새로운 화일은 >
56	빈도 화일 이름 >
57	사전 우선도의 숫자를 지정하십시오. >
58	사전을 경신할 수 있는 모드로 사용하겠읍니까? (Y or Newline / N)
59	빈도를 경신할 수 있는 모드로 사용하겠읍니까? (Y or Newline / N)
60	지금 사전을 읽는 중입니다.
61	사전 추가
62	사전 일람
63	등록
64	검색
65	패러미터 경신
66	빈도 저장
67	사전 정보
68	부속어 변경
69	종료
70	해석 문절수
71	소문절의 최대수
72	빈도 웨이트
73	소문절 길이 웨이트
74	자립어 길이 웨이트
75	최근 사용상황 웨이트
76	사전 우선도 웨이트
77	소문절 평가치 웨이트
78	대문절 길이 웨이트
79	소문절수 웨이트
80	숫자의 빈도
81	가나의 빈도
82	영숫자의 빈도
83	기호의 빈도
84	폐괄호의 빈도
85	부속어의 빈도
86	개괄호의 빈도
87	No.
88	Type.
89	주석
90	화일 이름
91	빈도 화일 이름
92	어휘수
93	우선도
94	등록 가능
95	빈도 경신 가능
96	사용중 이나
97	등록 패스워드
98	빈도 경신 패스워드
99	빈도
