#
#   $Id: ./wnnstat.msg $
#
#
# FreeWnn is a network-extensible Kana-to-Kanji conversion system.
# This file is part of FreeWnn.
# 
# Copyright Kyoto University Research Institute for Mathematical Sciences
#                 1987, 1988, 1989, 1990, 1991, 1992
# Copyright OMRON Corporation. 1987, 1988, 1989, 1990, 1991, 1992, 1999
# Copyright ASTEC, Inc. 1987, 1988, 1989, 1990, 1991, 1992
# Copyright FreeWnn Project 1999, 2000
# 
# Maintainer:  FreeWnn Project   <freewnn@tomo.gr.jp>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#
1	Env No.\t환경 이름\t참조수\t부속어\t사전수(사전No.)\t\t화일\n
2	Env No.\t환경 이름\t참조수\n
3	유저 이름:호스트 이름\t(소켓No.)\t환경 번호\n
4	No.\t종류\t별명\t화일\t\n
5	No.종류\t정/역\t어수\t경신(빈도) 사용 우선도\t[별명]\t화일[(빈도)]\t[파스워드(빈도)]\n
6	정 변환
7	역 변환
8	불
9	가
10	중
11	정지
12	Fid\t종류\t장소\t참조수\t\t화일 이름\n
13	사전
14	빈도
15	부속어
