#
#   $Id: ./libwnn.msg $
#
#
# FreeWnn is a network-extensible Kana-to-Kanji conversion system.
# This file is part of FreeWnn.
# 
# Copyright Kyoto University Research Institute for Mathematical Sciences
#                 1987, 1988, 1989, 1990, 1991, 1992
# Copyright OMRON Corporation. 1987, 1988, 1989, 1990, 1991, 1992, 1999
# Copyright ASTEC, Inc. 1987, 1988, 1989, 1990, 1991, 1992
# Copyright FreeWnn Project 1999, 2000
# 
# Maintainer:  FreeWnn Project   <freewnn@tomo.gr.jp>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
###	massage file for libwnn.a
### wnnerrmsg.c
#0	no_error 0
1	文件不存在。
#2	no_error 2
3	内存alloc失败。
#4	no_error 4
5	不是字典。
6	不是频度文件。
7	不是文法文件。
#8	no_error 8
9	字典表格满。
10	频度文件：不是指定的字典的频度文件。
#11	no_error 11
#12	no_error 12
#13	no_error 13
#14	no_error 14
#15	no_error 15
16	文件不能打开。
17	不是正确的频度文件。
18	不是正确的文法文件。
19	附属语的个数、向量长度等超过。
20	这个号码的字典、没有使用。
#21	no_error 21
#22	no_error 22
#23	no_error 23
24	文法文件的内容不正确
25	虚拟词性号码异常cixing.data不正确。
26	未定义的词性、定义了前端词性。
27	文法文件不能读取。
#28	no_error 28
#29	no_error 29
30	字典的项数超过。
31	变换后字符串的长度超过。
32	附属语解析域不够。
#33	no_error 33
34	次侯补域不够。
35	侯补 1个也没有
#36	no_error 36
#37	no_error 37
#38	no_error 38
#39	no_error 39
40	读音长度超过。
41	汉字长度超过。
42	指定的字典、不能登录。
43	读音的长度是0。
44	指定的字典、不能逆查。
45	只读的字典、登录/消除了。
46	环境中不存在的字典、登录了。
#47	no_error 47
#48	no_error 48
49	只读的频度、变更了。
50	指定的单字不存在。
#51	no_error 51
#52	no_error 52
#53	no_error 53
#54	no_error 54
#55	no_error 55
#56	no_error 56
#57	no_error 57
#58	no_error 58
#59	no_error 59
60	内存alloc失败。
#61	no_error 61
#62	no_error 62
#63	no_error 63
#64	no_error 64
#65	no_error 65
#66	no_error 66
#67	no_error 67
68	有出错发生。
69	好象有ｂｕｇ发生。
70	server死了。
71	alloc失败了。
72	不能和server连接。
73	通信规程的版本不符。
74	不是ｃＷｎｎ用户生成的环境。
#75	no_error 75
#76	no_error 76
#77	no_error 77
#78	no_error 78
#79	no_error 79
80	子目录不能创建。
#81	no_error 81
#82	no_error 82
#83	no_error 83
#84	no_error 84
#85	no_error 85
#86	no_error 86
#87	no_error 87
#88	no_error 88
#89	no_error 89
90	文件不能读取。
91	文件不能写出。
92	不是ｃＷｎｎ用户可读取的文件。
93	以上的文件不能读取。
94	password不对。
95	文件正在读取。
96	文件不能消除。
97	文件没有创建出来。
98	不是ｃＷｎｎ的文件。
99	文件的I-node和FILE_UNIQ不能一致。
100	词性文件太大。
101	词性文件太大。
102	词性文件不存在。
103	词性文件的内容不对。
#104	no_error 104
105	词性文件不能读取。
106	词性名不对。
107	词性号码不对。
#108	no_error 108
109	这个操作不支持。
110	password的输入文件不能打开。
111	uumrc文件不存在。
112	uumrc文件的形式错误。
113	以上环境不能创建。
114	这个ｃＷｎｎ用户、读取的文件没有。
115	字典的频度文件没有。
116	password的文件没有创建出来。
### jl.c
200	字典文件
201	没有。
202	创建?(Y/N)
203	频度文件
204	字典和频度 \"%s\" 的整合性没有。制作?(Y/N)
205	password_file
206	include 的等级超过。
207	file \"%s\"不能打开
208	文件 \"%s\" 的环境设定中、由于发生出错、设定中止。\n"
209	创建了。
210	directory
###
