#
#   $Id: ./uum.msg $
#
#
# FreeWnn is a network-extensible Kana-to-Kanji conversion system.
# This file is part of FreeWnn.
# 
# Copyright Kyoto University Research Institute for Mathematical Sciences
#                 1987, 1988, 1989, 1990, 1991, 1992
# Copyright OMRON Corporation. 1987, 1988, 1989, 1990, 1991, 1992, 1999
# Copyright ASTEC, Inc. 1987, 1988, 1989, 1990, 1991, 1992
# Copyright FreeWnn Project 1999, 2000
# 
# Maintainer:  FreeWnn Project   <freewnn@tomo.gr.jp>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
###	massage file for uum
### jhlp.c
1	\rｕｕｍ(かな漢字変換フロントエンドプロセッサ)\r\n
2	Mallocに失敗しました。
3	\r\nｕｕｍを終わります。\r\n
4	ｕｕｍからｕｕｍは起こせません。\n
5	候補が多過ぎて次候補が取り出せません。(如何)
6	JISコード: 
7	区点 : 
8	 (如何)
9	 jserverとの接続が切れています。(如何?)
10	 接続中・・・
11	 接続ホスト名 > 
12	 接続がうまくいきません。(如何?)
13	 接続に失敗しました。(如何?)
14	uumrc ファイルがありません。
15	前に戻る
16	 頻度:%c%d
17	評価値:%d 前端ベクトルNo.:%d
18	大文節評価値
19	  読み:
20	を削除しますか?(Y/N)
21	固定形式の辞書のエントリは削除出来ません。(如何)
22	リードオンリーの辞書のエントリは削除出来ません。(如何)
23	「
24	」を削除します。(Y/N)
25	リードオンリーの頻度は変更出来ません。(如何)
26	」の使用を中止します。(Y/N)
27	 はありません。(如何)
28	デフォルトのキーバインドが異常です。 %s\n
29	uumkey: %s を展開できません。\r\n
30	uumkey: %s(0x%x)のキーが二重定義です。at line %d (%s)(table No. %d).\r\n
31	辞書「
32	」の使用を再開します。(Y/N)
33	1:辞書 2:頻度 どちらにコメントをセットしますか。>
34	1 か 2 を指定して下さい。(如何)
35	コメント: 
36	固定形式辞書のエントリのコメントは変更出来ません。(如何)
37	リードオンリー辞書のエントリのコメントは変更出来ません。(如何)
38	登録終り:
39	登録始め:
40	辞書: 
41	  読み:
42	登録可能形式の辞書が一つもありません。
43	登録範囲が長過ぎます。(如何)
44	読みが長過ぎます。(如何)
45	現在 %d文節解析法を用いています。何文節解析法を用いますか ?
46	現在の%sは %dです、幾つにしますか ?
47	数字を入力してください。(如何)
48	正の数字を入力してください。(如何)
49	只今、辞書の頻度とユーザ辞書をセーブしています。
50	残念、辞書が多すぎます。
51	辞書が一つも有りません。
52	使用中
53	中断中
54	付属語ファイル名 >
55	新しい辞書は >
56	頻度ファイル名 >
57	辞書の優先度の数字を指定して下さい。 >
58	辞書を更新するモードで使いますか?(Y or Newline / N)
59	頻度を更新するモードで使いますか?(Y or Newline / N)
60	只今、辞書を読み込んでいます。
61	辞書追加
62	辞書一覧
63	登録
64	検索
65	パラメータ変更
66	頻度セーブ
67	辞書情報
68	付属語変更
69	終了
70	解析文節数
71	小文節の最大数
72	頻度重み
73	小文節長重み
74	自立語長重み
75	最近使用状況重み
76	辞書優先度重み
77	小文節の評価値重み
78	大文節長重み
79	小文節数重み
80	数字の頻度
81	カナの頻度
82	英数の頻度
83	記号の頻度
84	閉括弧の頻度
85	付属語の頻度
86	開括弧の頻度
87	No.
88	Type.
89	こめんと
90	ファイル名
91	頻度ファイル名
92	語彙数
93	優先度
94	登録可能
95	頻度更新可能
96	使用中か
97	登録パスワード
98	頻度更新パスワード
#99	\0
