.\"
.\"   $Id: ./zenko_dap.man $
.\"
.\"
.\" FreeWnn is a network-extensible Kana-to-Kanji conversion system.
.\" This file is part of FreeWnn.
.\" 
.\" Copyright Kyoto University Research Institute for Mathematical Sciences
.\"                 1987, 1988, 1989, 1990, 1991, 1992
.\" Copyright OMRON Corporation. 1987, 1988, 1989, 1990, 1991, 1992, 1999
.\" Copyright ASTEC, Inc. 1987, 1988, 1989, 1990, 1991, 1992
.\" Copyright FreeWnn Project 1999, 2000
.\" 
.\" Maintainer:  FreeWnn Project   <freewnn@tomo.gr.jp>
.\" 
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.\"
.TH JL_ZENKOUHO_DAIP \  "20 September 1991"
.SH 名称
.sv 1
.nf
.ta 0.1i 2.5i
jl_zenkouho_daip()  全候補が大文節かどうかの判定
.fi
.SH 形式
.sv 1
.nf
.ta 0.1i 3i
#include "jllib.h"
	
int	
jl_zenkouho_daip(buf)
struct wnn_buf *buf;	/* バッファ */
.fi
.SH 機能
.HP 0
.IP	
現在選択している全候補が大文節のものなら 1 を返す。


