#
#   $Id: ./wnnstat.msg $
#
#
# FreeWnn is a network-extensible Kana-to-Kanji conversion system.
# This file is part of FreeWnn.
# 
# Copyright Kyoto University Research Institute for Mathematical Sciences
#                 1987, 1988, 1989, 1990, 1991, 1992
# Copyright OMRON Corporation. 1987, 1988, 1989, 1990, 1991, 1992, 1999
# Copyright ASTEC, Inc. 1987, 1988, 1989, 1990, 1991, 1992
# Copyright FreeWnn Project 1999, 2000
# 
# Maintainer:  FreeWnn Project   <freewnn@tomo.gr.jp>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
1	Env No.\tô¿èºÇØ\tÙ¶äùí°\tÅÆÎÎ\tâ¤Ì¨í°(â¤Ì¨No.)\t\tÅÆÇµ\n
2	Env No.\tô¿èºÇØ\tÙ¶äùí°\n
3	ÆîÅÂÇØ:¤â¤é¤í¤îÇØ\t(ÚÙÄÇNo.)\tô¿èºæÀî£\n
4	No.\tê¡ùË\tÎÃúË\tÅÆÇµ\t\n
5	No.ê¡ùË\tÆß/ØË\të£í°\tÊÕä»(ó¢)ËðÆî óÀÇ¿×È\t[Ï÷ê¢]\tÅÆÇµ[(ó¢Ðù)]\t[password(ó¢Ðù)]\n
6	ØËüÈßÐ
7	ÆßüÈßÐ
8	Äâ
9	Æ«
10	Äã
11	ØôÅÏ
12	Fid\tê¡ùË\tÞÛÇÙ\tÙ¶äùí°\t\tÅÆÇµÇØ\n
13	â¤Ì¨
14	ó¢Ðù
15	ë£ÎÎ
