# Generated automatically from Makefile.in by configure.
#
#   $Id: ./Makefile.in $
#

#
# FreeWnn is a network-extensible Kana-to-Kanji conversion system.
# This file is part of FreeWnn.
# 
# Copyright Kyoto University Research Institute for Mathematical Sciences
#                 1987, 1988, 1989, 1990, 1991, 1992
# Copyright OMRON Corporation. 1987, 1988, 1989, 1990, 1991, 1992, 1999
# Copyright ASTEC, Inc. 1987, 1988, 1989, 1990, 1991, 1992
# Copyright FreeWnn Project 1999, 2000
# 
# Maintainer:  FreeWnn Project   <freewnn@tomo.gr.jp>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

include ../../../../makerule.mk

INSTALL         = $/usr/bin/install -c

MANDIR = $(LIBMANDIR)
MANSUFFIX = $(LIBMANSUFFIX)

all::

depend::

install.man:: access.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_access.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) access.man \
 $(DESTDIR)$(MANDIR)/js_access.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_access.$(MANSUFFIX)

install.man:: close.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_close.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) close.man \
 $(DESTDIR)$(MANDIR)/js_close.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_close.$(MANSUFFIX)

install.man:: connect.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_connect.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) connect.man \
 $(DESTDIR)$(MANDIR)/js_connect.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_connect.$(MANSUFFIX)

install.man:: dic_add.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_dic_add.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) dic_add.man \
 $(DESTDIR)$(MANDIR)/js_dic_add.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_dic_add.$(MANSUFFIX)

install.man:: dic_cr.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_dic_file_create.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) dic_cr.man \
 $(DESTDIR)$(MANDIR)/js_dic_file_create.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_dic_file_create.$(MANSUFFIX)

install.man:: dic_cr_cl.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_dic_file_create_client.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) dic_cr_cl.man \
 $(DESTDIR)$(MANDIR)/js_dic_file_create_client.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_dic_file_create_client.$(MANSUFFIX)

install.man:: dic_del.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_dic_delete.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) dic_del.man \
 $(DESTDIR)$(MANDIR)/js_dic_delete.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_dic_delete.$(MANSUFFIX)

install.man:: dic_info.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_dic_info.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) dic_info.man \
 $(DESTDIR)$(MANDIR)/js_dic_info.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_dic_info.$(MANSUFFIX)

install.man:: dic_lst.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_dic_list.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) dic_lst.man \
 $(DESTDIR)$(MANDIR)/js_dic_list.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_dic_list.$(MANSUFFIX)

install.man:: dic_lst_a.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_dic_list_all.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) dic_lst_a.man \
 $(DESTDIR)$(MANDIR)/js_dic_list_all.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_dic_list_all.$(MANSUFFIX)

install.man:: dic_use.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_dic_use.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) dic_use.man \
 $(DESTDIR)$(MANDIR)/js_dic_use.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_dic_use.$(MANSUFFIX)

install.man:: disconn.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_disconnect.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) disconn.man \
 $(DESTDIR)$(MANDIR)/js_disconnect.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_disconnect.$(MANSUFFIX)

install.man:: env_exist.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_env_exist.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) env_exist.man \
 $(DESTDIR)$(MANDIR)/js_env_exist.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_env_exist.$(MANSUFFIX)

install.man:: env_list.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_env_list.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) env_list.man \
 $(DESTDIR)$(MANDIR)/js_env_list.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_env_list.$(MANSUFFIX)

install.man:: env_stick.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_env_sticky.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) env_stick.man \
 $(DESTDIR)$(MANDIR)/js_env_sticky.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_env_sticky.$(MANSUFFIX)

install.man::
	@(SUFFIX=`echo $(DESTDIR)$(MANDIR)/js_env_sticky.* | sed -e 's,.*/[^\.]*.,,'`; \
	for i in js_env_un_sticky; do (set -x; \
	$(RM) $(DESTDIR)$(MANDIR)/$$i.*; \
	(cd $(DESTDIR)$(MANDIR); $(LN) js_env_sticky.$${SUFFIX} \
	$$i.$${SUFFIX})); \
	done)

install.man:: fl_com_s.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_file_comment_set.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) fl_com_s.man \
 $(DESTDIR)$(MANDIR)/js_file_comment_set.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_file_comment_set.$(MANSUFFIX)

install.man:: fl_disc.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_file_discard.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) fl_disc.man \
 $(DESTDIR)$(MANDIR)/js_file_discard.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_file_discard.$(MANSUFFIX)

install.man:: fl_info.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_file_info.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) fl_info.man \
 $(DESTDIR)$(MANDIR)/js_file_info.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_file_info.$(MANSUFFIX)

install.man:: fl_list.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_file_list.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) fl_list.man \
 $(DESTDIR)$(MANDIR)/js_file_list.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_file_list.$(MANSUFFIX)

install.man:: fl_list_a.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_file_list_all.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) fl_list_a.man \
 $(DESTDIR)$(MANDIR)/js_file_list_all.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_file_list_all.$(MANSUFFIX)

install.man:: fl_load.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_file_loaded.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) fl_load.man \
 $(DESTDIR)$(MANDIR)/js_file_loaded.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_file_loaded.$(MANSUFFIX)

install.man:: fl_load_l.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_file_loaded_local.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) fl_load_l.man \
 $(DESTDIR)$(MANDIR)/js_file_loaded_local.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_file_loaded_local.$(MANSUFFIX)

install.man:: fl_pswd_s.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_file_password_set.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) fl_pswd_s.man \
 $(DESTDIR)$(MANDIR)/js_file_password_set.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_file_password_set.$(MANSUFFIX)

install.man:: fl_read.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_file_read.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) fl_read.man \
 $(DESTDIR)$(MANDIR)/js_file_read.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_file_read.$(MANSUFFIX)

install.man:: fl_recv.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_file_receive.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) fl_recv.man \
 $(DESTDIR)$(MANDIR)/js_file_receive.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_file_receive.$(MANSUFFIX)

install.man:: fl_rm.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_file_remove.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) fl_rm.man \
 $(DESTDIR)$(MANDIR)/js_file_remove.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_file_remove.$(MANSUFFIX)

install.man:: fl_rm_cl.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_file_remove_client.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) fl_rm_cl.man \
 $(DESTDIR)$(MANDIR)/js_file_remove_client.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_file_remove_client.$(MANSUFFIX)

install.man:: fl_snd.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_file_send.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) fl_snd.man \
 $(DESTDIR)$(MANDIR)/js_file_send.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_file_send.$(MANSUFFIX)

install.man:: fl_stat.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_file_stat.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) fl_stat.man \
 $(DESTDIR)$(MANDIR)/js_file_stat.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_file_stat.$(MANSUFFIX)

install.man:: fl_wrt.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_file_write.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) fl_wrt.man \
 $(DESTDIR)$(MANDIR)/js_file_write.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_file_write.$(MANSUFFIX)

install.man:: fuz_get.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_fuzokugo_get.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) fuz_get.man \
 $(DESTDIR)$(MANDIR)/js_fuzokugo_get.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_fuzokugo_get.$(MANSUFFIX)

install.man:: fuz_set.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_fuzokugo_set.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) fuz_set.man \
 $(DESTDIR)$(MANDIR)/js_fuzokugo_set.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_fuzokugo_set.$(MANSUFFIX)

install.man:: hd_cr.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_hindo_file_create.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) hd_cr.man \
 $(DESTDIR)$(MANDIR)/js_hindo_file_create.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_hindo_file_create.$(MANSUFFIX)

install.man:: hd_cr_cl.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_hindo_file_create_client.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) hd_cr_cl.man \
 $(DESTDIR)$(MANDIR)/js_hindo_file_create_client.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_hindo_file_create_client.$(MANSUFFIX)

install.man:: hindo_set.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_hindo_set.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) hindo_set.man \
 $(DESTDIR)$(MANDIR)/js_hindo_set.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_hindo_set.$(MANSUFFIX)

install.man:: hinsi_dct.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_hinsi_dicts.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) hinsi_dct.man \
 $(DESTDIR)$(MANDIR)/js_hinsi_dicts.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_hinsi_dicts.$(MANSUFFIX)

install.man:: hinsi_lst.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_hinsi_list.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) hinsi_lst.man \
 $(DESTDIR)$(MANDIR)/js_hinsi_list.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_hinsi_list.$(MANSUFFIX)

install.man:: hinsi_nm.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_hinsi_name.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) hinsi_nm.man \
 $(DESTDIR)$(MANDIR)/js_hinsi_name.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_hinsi_name.$(MANSUFFIX)

install.man:: hinsi_num.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_hinsi_number.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) hinsi_num.man \
 $(DESTDIR)$(MANDIR)/js_hinsi_number.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_hinsi_number.$(MANSUFFIX)

install.man:: hinsi_t_s.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_hinsi_table_set.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) hinsi_t_s.man \
 $(DESTDIR)$(MANDIR)/js_hinsi_table_set.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_hinsi_table_set.$(MANSUFFIX)

install.man:: isconnect.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_isconnect.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) isconnect.man \
 $(DESTDIR)$(MANDIR)/js_isconnect.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_isconnect.$(MANSUFFIX)

install.man:: kanren.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_kanren.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) kanren.man \
 $(DESTDIR)$(MANDIR)/js_kanren.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_kanren.$(MANSUFFIX)

install.man:: kantan_d.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_kantan_dai.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) kantan_d.man \
 $(DESTDIR)$(MANDIR)/js_kantan_dai.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_kantan_dai.$(MANSUFFIX)

install.man:: kantan_s.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_kantan_sho.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) kantan_s.man \
 $(DESTDIR)$(MANDIR)/js_kantan_sho.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_kantan_sho.$(MANSUFFIX)

install.man:: kanzen_d.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_kanzen_dai.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) kanzen_d.man \
 $(DESTDIR)$(MANDIR)/js_kanzen_dai.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_kanzen_dai.$(MANSUFFIX)

install.man:: kanzen_s.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_kanzen_sho.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) kanzen_s.man \
 $(DESTDIR)$(MANDIR)/js_kanzen_sho.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_kanzen_sho.$(MANSUFFIX)

install.man:: kill.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_kill.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) kill.man \
 $(DESTDIR)$(MANDIR)/js_kill.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_kill.$(MANSUFFIX)

install.man:: mkdir.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_mkdir.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) mkdir.man \
 $(DESTDIR)$(MANDIR)/js_mkdir.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_mkdir.$(MANSUFFIX)

install.man:: open.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_open.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) open.man \
 $(DESTDIR)$(MANDIR)/js_open.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_open.$(MANSUFFIX)

install.man:: open_lang.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_open_lang.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) open_lang.man \
 $(DESTDIR)$(MANDIR)/js_open_lang.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_open_lang.$(MANSUFFIX)

install.man:: param_get.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_param_get.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) param_get.man \
 $(DESTDIR)$(MANDIR)/js_param_get.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_param_get.$(MANSUFFIX)

install.man::
	@(SUFFIX=`echo $(DESTDIR)$(MANDIR)/js_param_get.* | sed -e 's,.*/[^\.]*.,,'`; \
	for i in js_param_set; do (set -x; \
	$(RM) $(DESTDIR)$(MANDIR)/$$i.*; \
	(cd $(DESTDIR)$(MANDIR); $(LN) js_param_get.$${SUFFIX} \
	$$i.$${SUFFIX})); \
	done)

install.man:: set_lang.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_set_lang.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) set_lang.man \
 $(DESTDIR)$(MANDIR)/js_set_lang.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_set_lang.$(MANSUFFIX)

install.man::
	@(SUFFIX=`echo $(DESTDIR)$(MANDIR)/js_set_lang.* | sed -e 's,.*/[^\.]*.,,'`; \
	for i in js_get_lang; do (set -x; \
	$(RM) $(DESTDIR)$(MANDIR)/$$i.*; \
	(cd $(DESTDIR)$(MANDIR); $(LN) js_set_lang.$${SUFFIX} \
	$$i.$${SUFFIX})); \
	done)

install.man:: version.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_version.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) version.man \
 $(DESTDIR)$(MANDIR)/js_version.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_version.$(MANSUFFIX)

install.man:: who.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_who.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) who.man \
 $(DESTDIR)$(MANDIR)/js_who.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_who.$(MANSUFFIX)

install.man:: word_add.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_word_add.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) word_add.man \
 $(DESTDIR)$(MANDIR)/js_word_add.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_word_add.$(MANSUFFIX)

install.man:: word_cm_s.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_word_comment_set.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) word_cm_s.man \
 $(DESTDIR)$(MANDIR)/js_word_comment_set.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_word_comment_set.$(MANSUFFIX)

install.man:: word_del.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_word_delete.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) word_del.man \
 $(DESTDIR)$(MANDIR)/js_word_delete.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_word_delete.$(MANSUFFIX)

install.man:: word_info.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_word_info.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) word_info.man \
 $(DESTDIR)$(MANDIR)/js_word_info.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_word_info.$(MANSUFFIX)

install.man:: word_srch.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/js_word_search.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) word_srch.man \
 $(DESTDIR)$(MANDIR)/js_word_search.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/js_word_search.$(MANSUFFIX)

install.man::
	@(SUFFIX=`echo $(DESTDIR)$(MANDIR)/js_word_search.* | sed -e 's,.*/[^\.]*.,,'`; \
	for i in js_word_search_by_env; do (set -x; \
	$(RM) $(DESTDIR)$(MANDIR)/$$i.*; \
	(cd $(DESTDIR)$(MANDIR); $(LN) js_word_search.$${SUFFIX} \
	$$i.$${SUFFIX})); \
	done)
