# Generated automatically from Makefile.in by configure.
#
#   $Id: ./Makefile.in $
#

#
# FreeWnn is a network-extensible Kana-to-Kanji conversion system.
# This file is part of FreeWnn.
# 
# Copyright Kyoto University Research Institute for Mathematical Sciences
#                 1987, 1988, 1989, 1990, 1991, 1992
# Copyright OMRON Corporation. 1987, 1988, 1989, 1990, 1991, 1992, 1999
# Copyright ASTEC, Inc. 1987, 1988, 1989, 1990, 1991, 1992
# Copyright FreeWnn Project 1999, 2000
# 
# Maintainer:  FreeWnn Project   <freewnn@tomo.gr.jp>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

include ../../../makerule.mk

INSTALL         = $/usr/bin/install -c

MANSUFFIX = 1

install.man:: atod.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/atod.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) atod.man \
 $(DESTDIR)$(MANDIR)/atod.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/atod.$(MANSUFFIX)

install.man:: atof.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/atof.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) atof.man \
 $(DESTDIR)$(MANDIR)/atof.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/atof.$(MANSUFFIX)

install.man:: dtoa.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/dtoa.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) dtoa.man \
 $(DESTDIR)$(MANDIR)/dtoa.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/dtoa.$(MANSUFFIX)

install.man:: wddel.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/wddel.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) wddel.man \
 $(DESTDIR)$(MANDIR)/wddel.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/wddel.$(MANSUFFIX)

install.man:: wdreg.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/wdreg.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) wdreg.man \
 $(DESTDIR)$(MANDIR)/wdreg.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/wdreg.$(MANSUFFIX)

install.man:: wnntouch.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/wnntouch.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) wnntouch.man \
 $(DESTDIR)$(MANDIR)/wnntouch.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/wnntouch.$(MANSUFFIX)

install.man:: oldtonew.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(RM) $(DESTDIR)$(MANDIR)/oldatonewa.$(MANSUFFIX)*
	$(INSTALL) -c $(INSTMANFLAGS) oldtonew.man \
 $(DESTDIR)$(MANDIR)/oldatonewa.$(MANSUFFIX)
	-$(COMPRESSMANCMD) $(DESTDIR)$(MANDIR)/oldatonewa.$(MANSUFFIX)
